### PR TITLE
Add knatnetwork/github-runner

### PR DESCRIPTION
**Pull request by n0vad3v**
This PR adds the runner implementation built out by [n0vad3v](https://github.com/n0vad3v), also changes a typo from `DInd` to `DinD` (https://blog.nestybox.com/2019/09/14/dind.html).

This implementation is mainly focusing on simplicity as only a single `docker-compose.yml` is needed if you'd like to quickly register a runner. Of course, K8s deployment is also provided if there is a need to register many runners and mange replica by changing deployment's replica count.

Runner base OS is Ubuntu 20.04, and CentOS 7 will be added in near future, ARM64/AMD64 are supported.

Documentation site: https://runner.knat.network

### CODE REVIEW

**Comment by jonico** [comment]
@n0vad3v: Thank you for your contribution - in your patch you linked to the IssueOps projects for awesome-runner - I wonder whether this was a copy/paste issue or whether you have an IssueOps implementation for your solution - removed the IssueOps reference so far, if you give me 👍 I will merge

**Comment by n0vad3v** [comment]
Whoops, yes that's due to a copy/paste issue as there are no IssueOps in this implementation, thanks for removing it for me, let's merge this.

**Review by jonico — CHANGES_REQUESTED** [review]
Looking into https://github.com/knatnetwork/github-runner-kms - I see hardcoded references to GitHub.com but the row added states GitHub Enterprise Server support. Can you explain how GitHub Enterprise is supported?

**Comment by n0vad3v** [comment]
Update on this implementation, I have an article about this: https://nova.moe/unleash-github-actions-runner/ (Currently there is only Chinese version)

**Comment by jonico** [comment]
some of your badges links still seem to refer to goobernetes, can you adjust them to your project?

**Comment by n0vad3v** [comment]
Sure, fixed.

**Pull request merged**
